services:
  build:
    build: .
    container_name: build-synapseq
    platform: linux/amd64
    volumes:
      - .:/synapseq
    working_dir: /synapseq
    command:
      - /bin/sh
      - -c
      - |
        ./linux-build-libs.sh
        ./linux-build-synapseq.sh
        ./windows-build-libs.sh
        ./windows-build-synapseq.sh
        ./windows-create-installer.sh

  build-arm64:
    build: .
    container_name: build-synapseq-arm64
    platform: linux/arm64
    volumes:
      - .:/synapseq
    working_dir: /synapseq
    command:
      - /bin/sh
      - -c
      - |
        ./linux-build-libs.sh
        ./linux-build-synapseq.sh
